[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[window]
decorations = "Transparent" 
opacity = 0.5
blur = true
dynamic_title = true
padding.x = 10
padding.y = 10

[general]

live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]




