[General]
audioPlayerState=@Invalid()
contentViewState=@Invalid()
expandedFilterView=false
headerBarHeight=1e+05
headerBarIsMaximized=false
nowPlayingPreferLyric=false
playControlItemMuted=false
playControlItemVolume=100
playListPreferredWidth=0
playListState=@Invalid()
showPlaylist=true
