# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#111318

# Main text color
theme[main_fg]=#e1e2e9

# Title color for boxes
theme[title]=#e1e2e9

# Highlight color for keyboard shortcuts
theme[hi_fg]=#a4c9fe

# Background color of selected item in processes box
theme[selected_bg]=#1d2024

# Foreground color of selected item in processes box
theme[selected_fg]=#a4c9fe

# Color of inactive/disabled text
theme[inactive_fg]=#8d9199

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#d9bde3

# Background color of the percentage meters
theme[meter_bg]=#8d9199

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#d9bde3

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#a6bfff
theme[mem_box]=#bfe5ff
theme[net_box]=#b5bbf1
theme[proc_box]=#93bfff

# Box divider line and small boxes line color
theme[div_line]=#43474e

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#bfe5ff
theme[temp_mid]=#d0f9f4
theme[temp_end]=#a3afff

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#c5e3ff
theme[cpu_mid]=#9ecbff
theme[cpu_end]=#b3cdff

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#a6bfff
theme[free_mid]=#b3cdff
theme[free_end]=#93bfff

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#9ecbff
theme[cached_mid]=#93bfff
theme[cached_end]=#b3cdff

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#e0c2f9
theme[available_mid]=#b5bbf1
theme[available_end]=#a3afff

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#bfe5ff
theme[used_mid]=#c5e3ff
theme[used_end]=#c0deff

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#e0c2f9
theme[download_mid]=#b5bbf1
theme[download_end]=#a3afff

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#bfe5ff
theme[upload_mid]=#c5e3ff
theme[upload_end]=#c0deff

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#9ecbff
theme[process_mid]=#b3cdff
theme[process_end]=#a6bfff
